import type { Entry, EntrySource } from "./schemas";
import type { IsoString } from "./tz";

/** The clock: at most one running entry (derived from timestamps, so it survives an app kill). */
export interface ClockState {
  running: Entry | null;
}

export type ClockEventType = "entry.started" | "entry.ended" | "break.started" | "break.ended";

export interface ClockEvent {
  type: ClockEventType;
  entry: Entry;
}

export interface ClockTransition {
  state: ClockState;
  events: ClockEvent[];
}

export interface StartInput {
  /** New entry id (UUIDv7 generated by the caller). */
  id: string;
  clientId: string;
  jobId?: string | null;
  now: IsoString;
  source: EntrySource;
}

export type SwitchInput = Omit<StartInput, "source"> & { source?: EntrySource };

export interface At {
  now: IsoString;
}

export const IDLE: ClockState = Object.freeze({ running: null });

const iso = (t: IsoString) => new Date(Date.parse(t)).toISOString();
const sec = (t: IsoString) => Math.floor(Date.parse(t) / 1000);
const unchanged = (state: ClockState): ClockTransition => ({ state, events: [] });

export function isOnBreak(entry: Entry | null | undefined): boolean {
  return !!entry && !entry.endedAt && !!entry.breakStartedAt;
}

function newEntry(input: StartInput): Entry {
  const now = iso(input.now);
  return {
    id: input.id,
    clientId: input.clientId,
    jobId: input.jobId ?? null,
    startedAt: now,
    endedAt: null,
    breakSeconds: 0,
    breakStartedAt: null,
    note: "",
    source: input.source,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  };
}

function closeBreak(entry: Entry, now: IsoString): Entry {
  if (!entry.breakStartedAt) return entry;
  const extra = Math.max(0, sec(now) - sec(entry.breakStartedAt));
  return { ...entry, breakSeconds: entry.breakSeconds + extra, breakStartedAt: null, updatedAt: iso(now) };
}

/** Events + final entry for ending `entry` at `now` (closing any open break first). */
function finish(entry: Entry, now: IsoString): ClockEvent[] {
  const events: ClockEvent[] = [];
  let e = entry;
  if (isOnBreak(e)) {
    e = closeBreak(e, now);
    events.push({ type: "break.ended", entry: e });
  }
  const end = Math.max(Date.parse(now), Date.parse(e.startedAt));
  e = { ...e, endedAt: new Date(end).toISOString(), updatedAt: iso(now) };
  events.push({ type: "entry.ended", entry: e });
  return events;
}

function start(input: StartInput, prior: ClockEvent[] = []): ClockTransition {
  const entry = newEntry(input);
  return { state: { running: entry }, events: [...prior, { type: "entry.started", entry }] };
}

/** Start an entry. Same client + job already running → no-op; a different one → switch. */
export function clockIn(state: ClockState, input: StartInput): ClockTransition {
  const cur = state.running;
  if (!cur) return start(input);
  if (cur.clientId === input.clientId && (cur.jobId ?? null) === (input.jobId ?? null)) return unchanged(state);
  return start(input, finish(cur, input.now));
}

/** End the running entry and start the next at the same instant (or just start, when idle). */
export function switchJob(state: ClockState, input: SwitchInput): ClockTransition {
  const cur = state.running;
  const source = input.source ?? cur?.source ?? "manual";
  return start({ ...input, source }, cur ? finish(cur, input.now) : []);
}

export function startBreak(state: ClockState, { now }: At): ClockTransition {
  const cur = state.running;
  if (!cur || isOnBreak(cur)) return unchanged(state);
  const entry: Entry = { ...cur, breakStartedAt: iso(now), updatedAt: iso(now) };
  return { state: { running: entry }, events: [{ type: "break.started", entry }] };
}

export function endBreak(state: ClockState, { now }: At): ClockTransition {
  const cur = state.running;
  if (!cur || !isOnBreak(cur)) return unchanged(state);
  const entry = closeBreak(cur, now);
  return { state: { running: entry }, events: [{ type: "break.ended", entry }] };
}

/** Stop the running entry. Nothing running → no-op with no events. */
export function clockOut(state: ClockState, { now }: At): ClockTransition {
  const cur = state.running;
  if (!cur) return unchanged(state);
  return { state: IDLE, events: finish(cur, now) };
}

/** When to fire the "still clocked in?" nudge for a running entry; null once it has ended. */
export function nudgeAt(entry: Pick<Entry, "startedAt" | "endedAt">, nudgeAfterHours = 10): IsoString | null {
  if (entry.endedAt) return null;
  return new Date(Date.parse(entry.startedAt) + Math.round(nudgeAfterHours * 3_600_000)).toISOString();
}
